language: cpp
dist: bionic
addons:
  apt:
    packages:
      - cmake
      - lcov
      - g++-7
      - python-pip
compiler:
  - gcc
os:
  - linux
install:
  - sudo pip install conan    
script:
  - export CXX=g++-7
  - export CC=gcc-7
  - export CODECOV_TOKEN="d3d577f7-24ba-43c6-aa89-efb6e47f07db"
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - mkdir install
  - conan install ..
  - cmake .. -DHSM_GCC_COVERAGE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install
  - cmake --build . --target install
  - ctest -VV
  - ./bin/simple_sc
  - ./bin/simple_euml
  - ./bin/simple_hsm
  - ./bin/complex_switch
  - ./bin/complex_sc
  - ./bin/complex_euml
  - ./bin/complex_hsm
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
